### ISSUE TITLE
Create/document workflow for properly working in a dm bon

### ISSUE THREAD

**Issue by kmexter** [vliz-be-opsci/vliz-be-opsci.github.io#16]
Whenever we have a new project in DM BON, we should create the necessary polices, licences, workflow documentation so that the users of that know what they should be doing when adding stuff to the repos of that project. To avoid doing this one-by-one, we should itemise the likely actions that will be taken (e.g. always create a README not a readme, always add a licence, always use CSV rather than xls, etcetc depending on the project's desires), document then (for humans at least), and then one can mix and match from this when a new project is created.

**Comment by cedricdcc** [comment]
Link back to current README of dmbon-assistant [README](https://github.com/vliz-be-opsci/dmbon-assistant/blob/main/README.md)
