### ISSUE TITLE
Make a licence workflow

### ISSUE THREAD

**Issue by kmexter** [vliz-be-opsci/vliz-be-opsci.github.io#17]
To ensure we can set the licences we want, we should put the necessary text needed for the set of CC's (for data) and the preferred software licences (which github already offer immediately anyway). These can be chosen from by any project working in DM BON

**Comment by marc-portier** [comment]
beware license confif per crate has a number of aspects
- metadata in github
- LICENSE file in the repo
- actual semantic setting inside the ro-crate metadata file


they all should say the same thing!


todo 
1. @cedricdcc make a separate issue to implement support for this in dmbon-assistant (i.e. have end user select a license then cover the other aspects --> produce / overwrite (or flag) 
2. decide from which list we want to start from, options are (i) github built in tlist, (ii) [spdx list](https://spdx.org/licenses/) or (iii) [the opendefinitions list](https://opendefinition.org/licenses/)
