### ISSUE TITLE
[REQUEST]: DM BON Assistent documentation 

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/vliz-be-opsci.github.io#34]
Please provide an updated version of the dmbon assistent documentation 

currently documentation is located in 2 files: dmbon.html & dmbon.md (with navigation currently going to dmbon.html) --> could this be located to one file? 

+please also update dmbon in _data/software-applications.md

**Comment by marc-portier** [comment]
let us just keep this in md, no?
(removing the html file and making sure the md takes its place...)
