### ISSUE TITLE
Add past participations

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/vliz-be-opsci.github.io#4]
Add past participations to the _data/participations.yml

have this years events on the main page 
and link to separate page that lists all the events with a bit more explanation

**Comment by kmexter** [comment]
Extra publications: 
https://www.frontiersin.org/articles/10.3389/fmars.2020.572680/full
https://zenodo.org/record/5093125#.YozKkKhBxnI

Extra events: 
conference presentation https://biss.pensoft.net/article/58938/; 
EOSC Life FAIR Hackathon: hmm, does not really have an EOSC Life link, so will wait until that happens
Our FAIR course! Once Shanna has made it public

**Comment by marc-portier** [comment]
is this still relevant for the new theme ?
