### ISSUE TITLE
[REQUEST]: vision & goals documentation

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/vliz-be-opsci.github.io#43]
please provide documentation on the vision & goals of open science at vliz in open-science-at-vliz.md

**Comment by kmexter** [comment]
I'd like to do this today but can someone tell me where the file is I need to edit? I really cannot find anything called vision and goals

**Comment by laurianvm** [comment]
In the refactor/move-to-new-jekyll-vliz-theme branch (https://github.com/vliz-be-opsci/vliz-be-opsci.github.io/tree/refactor/move-to-new-jekyll-vliz-theme) you will find open-science-at-vliz.md - it is this file that should contain the documentation on vision and goals

**Comment by kmexter** [comment]
I think this is referring to https://github.com/vliz-be-opsci/vliz-be-opsci.github.io/blob/dev/open-science-at-vliz.md and I am moving that on to Marc to start off - I can edit it then
