### ISSUE TITLE
[REQUEST]: General Open Science documentation

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/vliz-be-opsci.github.io#45]
please provide content on the goals/aims of open science, the components it consists of and a short description on open science principles (using provided documentation & people) in open-science.md*
+also including FAIR principles? provenance?

*currently provided as single page for now - once content gets bulky enough this can be separated into different files

(side note: principles might be left out of for first release)

**Comment by kmexter** [comment]
here also, I'd like to do this today but don't know where the file it I should edit....

**Comment by laurianvm** [comment]
open-science.md can also be found and edited in the refactor/move-to-new-jekyll-vliz-theme branch (https://github.com/vliz-be-opsci/vliz-be-opsci.github.io/tree/refactor/move-to-new-jekyll-vliz-theme)

**Comment by kmexter** [comment]
wrote something on https://github.com/vliz-be-opsci/vliz-be-opsci.github.io/blob/dev/open-science.md
