### ISSUE TITLE
put themes on the project + categorical search

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/vliz-be-opsci.github.io#6]
An extra class can be added to each project box that is the categorical value of the project eg (python, exe, etc).

The extra class can be used to add diff styling to each class.

the search can be a display block on the css of the item boxes.

**Comment by kmexter** [comment]
OK, so being linked data we should actually use a controlled vocab!....but I think that is going a bit overboard :-D
Just some thoughts on what is there now:
DM BON - data management and data publishing. Is this a "tool", or is it "data management"?
AIS - goereferencing in action? Well, it is at least a "tool"
Ro-Crate: given we use it and develop things around it, should we not mention this as a project? Under it we can link to the things we are developing for it or where we are using it. This would be a "data packaging" object
All the PY.... and ...PY things are: "python libraries". Some are "ocean data" specific. 
NS: hmm, well it is related to "ontolgies", and I guess there is nothing wrong with having just one object in a category...
